const { MongoClient } = require("mongodb");

/*

415:
default route - code checks for authentication cookie

if no cookie.. present login or register forms.
register form asks for user_ID and password, enter into mongo database.
on submission, keys looked up in database if they're a valid pairing.
	if so, set cookie (expires in 1 minute).
	if not, link back to default endpoint and display error message.

if there's a cookie.. message confirms and prints cookie value.

"All output views generated by the program must contain a link to an endpoint route which prints all the cookies which are active on that app and provides a link to an endpoint route that resets/clears the cookie."
so reset (show successful message after reset) endpoint, and print mongo logins endpoint
every page must link to both of the above.

-

routes:
  default - check for cookie
    if none, go to login
    if so, print details
  login - login form that creates existing cookie
    set so it lasts 1 minute
  register - register form that inserts record and sets cookie after validation
    set so it lasts 1 minute
  
  (X) create default route
  (X) check for cookie in route
  (_) create login route
  (_) if no cookie, redirect to login route
  (_) create form for login page

*/

// The uri string must be the connection string for the database (obtained on Atlas).

const uri = "mongodb+srv://<user>:<password>@ckmdb.5oxvqja.mongodb.net/?retryWrites=true&w=majority";

// --- This is the standard stuff to get it to work on the browser
const cookieParser = require('cookie-parser');
const express = require('express');

const app = express();
const port = 3000;
app.listen(port);
console.log('Server started at http://localhost:' + port);

app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser()); // need this to show cookies

// ROUTES //

app.get('/', function(req, res) {
  const myquery = req.query;

  var mycookies = req.cookies;
  var content = "";

  console.log(mycookies);

  if (JSON.stringify(mycookies) != "{}") { // is it empty?
   content += "Results: " + JSON.stringify(mycookies);
  } else {
    content += "NO RESULTS! <br> Redirecting to <a href='/login'>login page</a>...";
    content += "<script>setTimeout(function(){window.location='/login';},2000)</script>"
  }
  res.send(content);
});

app.get('/login', function(req, res) {
  content = "<p>Login <a href='https://bingus.com'>here.</a><p>"
  res.send(content);
});

app.get('/set', function(req, res) {
  res.cookie('name', 'value', {maxAge : 20000});
  res.send("set!");
});

app.get('/show', function(req, res) {
  mycookies = req.cookies;
  res.send("here: ", mycookies);
});











app.get('/say/:name', function(req, res) {
  res.send('Hello ' + req.params.name + '!');
});


// Route to access database:
app.get('/api/mongo/:item', function(req, res) {
const client = new MongoClient(uri);
const searchKey = "{ partID: '" + req.params.item + "' }";
console.log("Looking for: " + searchKey);

async function run() {
  try {
    const database = client.db('ckmdb');
    const parts = database.collection('cmps415');

    // Hardwired Query for a part that has partID '12345'
    // const query = { partID: '12345' };
    // But we will use the parameter provided with the route
    const query = { partID: req.params.item };

    const part = await parts.findOne(query);
    console.log(part);
    res.send('Found this: ' + JSON.stringify(part));  //Use stringify to print a json

  } finally {
    // Ensures that the client will close when you finish/error
    await client.close();
  }
}
run().catch(console.dir);
});
